# Maximum weight (once this limit is reached a player's speed will no longer decrease)
# a higher value means there will be a higher variance in speed
weightLimit: 500

# If set to true, upon reaching [weightLimit], the player will be unable to walk
# until their weight decreases.
disableMovement: false

# If set to true, upon reaching [weightLimit], the player will be blinded
# This helps with a spigot issue where players can sprint jump to bypass speed changes
blindAtMax: true

# Sets the walk speed when a player has an empty inventory(max) and when a player has weight greater than
# or equal to the weight limit(min) (Note: .20 is the default walk speed in Minecraft)
# values must be between 1.0 and 0.0 and min speed must be less than max speed
maxWalkSpeed: .30
minWalkSpeed: .05

# The % of the weight capacity that a player must reach before their speed begins to decrease
# Up until this value the player will have the max walk speed. For example if the value is set to .50. The player will
# be at max speed of .30 until they reach 50% of the weight limit. Then it will begin to decrease.
beginSlowdown: 0.0

# Time in seconds where the plugin will recalculate each player's weight
# A lower number results in more frequent updates
checkInventoryTimer: 2

# Include names of the worlds you would like to be affected by the plugin.
# if you would like it to affect every world then leave this empty
worlds:
#  - world
#  - otherWorldToEnable

# if set to true only the armor slots will be counted for a player's weight
armorOnly: false

# Sets the default weight for all items not specified
defaultWeight: 1

# List of materials and their weights, if a material is not listed then it assumes the default value
# list of materials can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

# PRIORITY ORDER loreTags >> customItemWeights >> materialWeights

# You can add a custom "lore tag" to the lore of an item and this plugin will determine the weight.
# In this example if you have a line in the item lore that says "Weight: 110", the weight for that
# item will be 110! The tag "Weight:" must be in the lore string for the plugin to pick it up.
loreTag: 'Weight:'
capacityTag: 'Capacity:'

# example weight by material
materialWeights:
  - material: IRON_PICKAXE
    weight: 5
  - material: IRON_SWORD
    weight: 10
  - material: BROWN_MUSHROOM
    weight: 0.5
  - material: WHEAT_SEEDS
    weight: 1.5
  - material: DIAMOND_SWORD
    weight: 5

# Weight by item name
customItemWeights:
  - name: Diamond Sword of Doom
    weight: 20

modelIdWeights:
  - modelId: 1000
    weight: 13

# Limit the amount of a specific item that player's can have in their inventory.
# In this example, a player can not have more than 5 shulker boxes in their inventory.
# When player is over the limit they will be treated as if they've gone over the max weight.
itemLimits:
  - limit: 5
    modelId: 1000
  - material: SHULKER_BOX
    limit: 5
    # permission: 'somepermission.node' optionally add a permission for the limit
